import type { LogoRef } from "./types";

/** Intrinsic size (px) of each trimmed logo in /public/logos, used by next/image. */
export const logoSizes: Record<string, [number, number]> = {
  fortinet: [164, 27],
  radware: [243, 41],
  checkpoint: [243, 53],
  claroty: [281, 53],
  microsoft: [135, 90],
  huawei: [104, 105],
  hytera: [181, 75],
  dahua: [148, 44],
  hikvision: [174, 23],
  spacex: [190, 24],
  iceye: [192, 50],
  cloudflare: [186, 59],
  dragos: [196, 64],
  ibm: [147, 60],
  paloalto: [238, 43],
  ericsson: [100, 88],
  nokia: [215, 36],
  cisco: [109, 97],
  thales: [227, 27],
  "rohde-schwarz": [235, 54],
  mavenir: [147, 26],
  frequentis: [188, 33],
  honeywell: [206, 55],
  siemens: [138, 32],
  schneider: [141, 85],
  abb: [85, 49],
  emerson: [223, 94],
  percepto: [246, 37],
  rockwell: [228, 54],
  hexagon: [241, 75],
  viasat: [196, 70],
  iai: [125, 79],
  cybernetica: [360, 45],
  trendmicro: [186, 72],
  crowdstrike: [136, 61],
  rafael: [197, 43],
  elbit: [189, 65],
  waterfall: [233, 62],
  levira: [155, 47],
  google: [88, 90],
  mandiant: [300, 60],
};

const c = (logo: string | undefined, name: string, estonian = false): LogoRef =>
  estonian ? { logo, name, estonian } : { logo, name };

export const C = {
  fortinet: c("fortinet", "Fortinet"),
  radware: c("radware", "Radware"),
  checkpoint: c("checkpoint", "Check Point"),
  claroty: c("claroty", "Claroty"),
  microsoft: c("microsoft", "Microsoft"),
  huawei: c("huawei", "Huawei"),
  hytera: c("hytera", "Hytera"),
  dahua: c("dahua", "Dahua Technology"),
  hikvision: c("hikvision", "Hikvision"),
  spacex: c("spacex", "SpaceX"),
  iceye: c("iceye", "ICEYE"),
  cloudflare: c("cloudflare", "Cloudflare"),
  dragos: c("dragos", "Dragos"),
  ibm: c("ibm", "IBM"),
  paloalto: c("paloalto", "Palo Alto Networks"),
  ericsson: c("ericsson", "Ericsson"),
  nokia: c("nokia", "Nokia"),
  cisco: c("cisco", "Cisco"),
  thales: c("thales", "Thales"),
  rohde: c("rohde-schwarz", "Rohde & Schwarz"),
  mavenir: c("mavenir", "Mavenir"),
  frequentis: c("frequentis", "Frequentis"),
  honeywell: c("honeywell", "Honeywell"),
  siemens: c("siemens", "Siemens"),
  schneider: c("schneider", "Schneider Electric"),
  abb: c("abb", "ABB"),
  emerson: c("emerson", "Emerson"),
  percepto: c("percepto", "Percepto"),
  rockwell: c("rockwell", "Rockwell Automation"),
  hexagon: c("hexagon", "Hexagon"),
  viasat: c("viasat", "Viasat"),
  iai: c("iai", "Israel Aerospace Industries (IAI)"),
  cybernetica: c("cybernetica", "Cybernetica", true),
  trendmicro: c("trendmicro", "Trend Micro"),
  crowdstrike: c("crowdstrike", "CrowdStrike"),
  rafael: c("rafael", "Rafael Advanced Defense Systems"),
  elbit: c("elbit", "Elbit Systems"),
  waterfall: c("waterfall", "Waterfall Security"),
  levira: c("levira", "Levira", true),
  google: c("google", "Google"),
  mandiant: c("mandiant", "Mandiant (Google Cloud)"),
  // Shown as text (no logo) in the deck
  nortal: c(undefined, "Nortal", true),
  rantelon: c(undefined, "Rantelon", true),
  planet: c(undefined, "Planet"),
  amazonLeo: c(undefined, "Amazon Leo"),
  airbus: c(undefined, "Airbus Space"),
  maxar: c(undefined, "Maxar"),
} satisfies Record<string, LogoRef>;

/** Deck slide 8 — candidate anchor companies per core domain (order as in the deck). */
export const candidatesByDomain: LogoRef[][] = [
  [
    C.fortinet, C.microsoft, C.cloudflare, C.crowdstrike, C.dragos, C.claroty, C.ibm,
    C.cybernetica, C.waterfall, C.radware, C.checkpoint, C.trendmicro, C.paloalto, C.nortal,
  ],
  [
    C.ericsson, C.cisco, C.elbit, C.huawei, C.cybernetica, C.hytera, C.nokia, C.rohde,
    C.thales, C.frequentis, C.mavenir, C.levira, C.rantelon,
  ],
  [
    C.honeywell, C.rockwell, C.hexagon, C.hikvision, C.siemens, C.dahua, C.schneider,
    C.abb, C.emerson, C.percepto, C.rafael, C.cybernetica,
  ],
  [
    C.spacex, C.iceye, C.viasat, C.thales, C.iai, C.levira, C.planet, C.amazonLeo,
    C.airbus, C.maxar,
  ],
];

/** Deck slide 9 — five priority company pools (order as in the deck). */
export const pools: LogoRef[][] = [
  [C.honeywell, C.emerson, C.siemens, { ...C.schneider, mark: "*" }, C.abb],
  [C.iai, C.rafael, C.elbit],
  [C.hikvision, C.huawei, C.hytera, C.dahua],
  [C.google, C.mandiant, C.crowdstrike, C.spacex, C.microsoft, C.thales],
  [C.fortinet, C.checkpoint, C.claroty, C.radware],
];
